### ISSUE TITLE
Support moment-timezone

### ISSUE THREAD

**Issue by euangoddard** [ksloan/moment-mini#4]
I don't think this is the right place to raise this issue, but not sure where would be more appropriate. I use this library to avoid packaging the locales for moment.js and it works fantastically. Now I've added moment-timezone as a dependency and this imports moment in it's code (which is also installs as a full dependency). So now I lose all the benefits of moment-mini.

I was wondering if you'd be prepared to support a mini version of `moment-timezone` that references `moment-mini` in codebase. If you're not up for it, could you let me know how you automatically keep up-to-date with moment.js releases so that I might implement something myself?

Thanks in advance!

**Comment by gkiely** [comment]
@euangoddard This would be awesome!

Hopefully @ksloan can add moment-timezone.

Otherwise maybe there's a way to track it by github releases: https://github.com/moment/moment-timezone/releases.atom

**Comment by jhchill666** [comment]
Same applies for [moment-range](https://github.com/rotaready/moment-range), and [moment-duration-format](https://github.com/jsmreese/moment-duration-format), and undoubtedly any other lib/plugin based on `momemt`.

Easy enough to alias moment out if using Webpack or the like mind you

**Comment by DannyFeliz** [comment]
I need this

**Comment by ksloan** [comment]
I think this is out of scope for this repo -- but could you just fork moment-timezone and replace the moment dependency with moment-mini?
