### ISSUE TITLE
Repository is locked for PRs !!!

### ISSUE THREAD

**Issue by senseijames** [ksloan/moment-mini#8]
Hello, Good Sir!

Thank you so much for creating this package!  Being able to cull localization solves a big problem for us!

But I'm trying to update `moment.min.js` and `moment.d.ts` to the latest version from _moment_, and the repo won't let me push to a new branch!!!

<img width="809" alt="Screen Shot 2022-08-01 at 6 03 07 PM" src="https://user-images.githubusercontent.com/915563/182270462-98bb644f-e05a-4889-9827-ffacbd835216.png">

And when I try to add files manually via github.com
<img width="843" alt="Screen Shot 2022-08-01 at 6 04 02 PM" src="https://user-images.githubusercontent.com/915563/182270573-f8aa0812-3417-4c87-9763-3fbc10a1ae86.png">

I get disappointments!!

<img width="573" alt="Screen Shot 2022-08-01 at 6 05 29 PM" src="https://user-images.githubusercontent.com/915563/182270606-8baee98e-26ca-48c6-a115-8b25502c8432.png">

Is there anyway you might deign to loosen your fair repo's chastity belts so I may share the fruits of these update goodnesses with the worlds ???

🤗 🤗 🤗 
James

**Comment by ksloan** [comment]
Hey James, thanks for the contribution, I think you need to fork the repository and then do a PR request from there.

**Comment by ksloan** [comment]
I just pushed an update to 2.29.4 hopefully that will fix any issues you have.

**Comment by senseijames** [comment]
Awesome sauce!  You are an officer and a gentleman, good Sir!
